[tool.poetry]
name = "brasil-data"
packages = [
    {include = "brdata"}
]
version = "0.12.2"
description = "Fontes de dados do mercado financeiro brasileiro"
authors = ["Gabriel Guarisa <gabrielguarisa@gmail.com>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/gabrielguarisa/brdata"
homepage = "https://github.com/gabrielguarisa/brdata"
keywords = ["data", "dados", "brasil", "br", "brazil", "finance", "financeiro", "mercado"]

[tool.poetry.dependencies]
python = ">=3.9,<3.13"
pandas = "^2.1.3"
html5lib = "^1.1"
lxml = "^4.9.3"
xlrd = "^2.0.1"
requests = "^2.31.0"
appdirs = "^1.4.4"
cachier = "^2.2.1"
random-user-agent = "^1.0.1"
beautifulsoup4 = "^4.12.2"
importlib-metadata = "^6.8.0"
cache-decorator = "^2.1.15"

[tool.poetry.group.dev.dependencies]
ruff = "^0.1.5"
pytest = "^6.2.4"
pytest-cov = "^3.0.0"
ipykernel = "^6.26.0"
lazydocs = "^0.4.8"

[tool.black]
# https://github.com/psf/black
target-version = ["py37"]
line-length = 88
color = true

exclude = '''
/(
    \.git
    | \.hg
    | \.mypy_cache
    | \.tox
    | \.venv
    | _build
    | buck-out
    | build
    | dist
    | env
    | venv
)/
'''

[tool.isort]
# https://github.com/timothycrosley/isort/
py_version = 37
line_length = 88

known_typing = [
  "typing",
  "types",
  "typing_extensions",
  "mypy",
  "mypy_extensions",
]
sections = [
  "FUTURE",
  "TYPING",
  "STDLIB",
  "THIRDPARTY",
  "FIRSTPARTY",
  "LOCALFOLDER",
]
include_trailing_comma = true
profile = "black"
multi_line_output = 3
indent = 4
color_output = true

[tool.pytest.ini_options]
addopts = "-p no:warnings --cov-report term-missing --cov=brdata"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
