[tool.poetry]
name = "brasil-data"
packages = [
    {include = "brdata"}
]
version = "v1.0.1"
description = "Brazilian financial market data sources"
authors = ["Gabriel Guarisa <gabrielguarisa@gmail.com>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/gabrielguarisa/brdata"
homepage = "https://github.com/gabrielguarisa/brdata"
keywords = ["data", "dados", "brasil", "br", "brazil", "finance", "financeiro", "mercado"]

[tool.poetry.dependencies]
python = ">=3.9,<3.13"
pandas = ">=1.5.3"
html5lib = ">=1.1"
requests = ">=2.31.0"
random-user-agent = "^1.0.1"
beautifulsoup4 = ">=4.11.2"
cache-decorator = "^2.1.15"

[tool.poetry.group.dev.dependencies]
ruff = "^0.1.5"
pytest = ">=7.4.3"
pytest-cov = "^4.1.0"
ipykernel = "^6.26.0"
lazydocs = "^0.4.8"
mkdocs = "^1.5.3"
mkdocs-awesome-pages-plugin = "^2.9.2"

[tool.black]
# https://github.com/psf/black
target-version = ["py37"]
line-length = 88
color = true

exclude = '''
/(
    \.git
    | \.hg
    | \.mypy_cache
    | \.tox
    | \.venv
    | _build
    | buck-out
    | build
    | dist
    | env
    | venv
)/
'''

[tool.isort]
# https://github.com/timothycrosley/isort/
py_version = 37
line_length = 88

known_typing = [
  "typing",
  "types",
  "typing_extensions",
  "mypy",
  "mypy_extensions",
]
sections = [
  "FUTURE",
  "TYPING",
  "STDLIB",
  "THIRDPARTY",
  "FIRSTPARTY",
  "LOCALFOLDER",
]
include_trailing_comma = true
profile = "black"
multi_line_output = 3
indent = 4
color_output = true

[tool.pytest.ini_options]
addopts = "-p no:warnings --cov-report term-missing --cov=brdata"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
